#!/bin/bash

# services-go/cmd/notifications.

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /overleaf/bin/go/notifications >> /var/log/overleaf/notifications.log 2>&1
