#!/bin/bash

# services-go/cmd/linked-url-proxy.

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /overleaf/bin/go/linked-url-proxy >> /var/log/overleaf/linked-url-proxy.log 2>&1
