/**
 * The icons the unfilled font carries.
 *
 * Generated from services/web/frontend/fonts/material-symbols/unfilled-symbols.mjs.
 * The unfilled face is a partial slice of the font: an icon not in this list
 * has no outline glyph, and asking for one would draw its name as text. The
 * type makes that a compile error instead.
 */

export const unfilledSymbols = [
  'account_balance',
  'arrow_back_ios_new',
  'arrow_circle_up',
  'auto_delete',
  'autorenew',
  'block',
  'book_5',
  'brush',
  'cached',
  'call_split',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'code',
  'content_copy',
  'create_new_folder',
  'delete',
  'delete_forever',
  'description',
  'domain',
  'edit',
  'edit_square',
  'error',
  'experiment',
  'find_replace',
  'format_strikethrough',
  'forum',
  'functions',
  'globe',
  'group',
  'help',
  'image',
  'info',
  'integration_instructions',
  'lightbulb',
  'lightbulb_2',
  'lock',
  'lock_open',
  'mail',
  'mode_comment',
  'more_vert',
  'neurology',
  'note_add',
  'notifications',
  'open_in_new',
  'password',
  'person',
  'person_edit',
  'picture_as_pdf',
  'push_pin',
  'rate_review',
  'report',
  'search',
  'settings',
  'shuffle',
  'smart_toy',
  'space_dashboard',
  'spellcheck',
  'star',
  'strikethrough_s',
  'table_chart',
  'text_snippet',
  'thumb_down',
  'thumb_up',
  'transform',
  'tune',
  'turn_left',
  'upload',
  'upload_file',
  'visibility',
  'visibility_off',
  'warning',
  'web_asset',
  'whatshot',
  'wifi_off',
] as const

export type AvailableUnfilledIcon = (typeof unfilledSymbols)[number]
