#!/bin/bash

# services-go/cmd/project-history.

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /overleaf/bin/go/project-history >> /var/log/overleaf/project-history.log 2>&1
