// Everything an operator used to set with an environment variable, and where
// it lands in Settings.
//
// The whole point of this table is that the admin page needs no knowledge of
// any particular setting: it renders whatever is here, and a setting is added
// by adding a row. The `env` column is what the value used to be read from,
// and is used once -- to seed the stored value on a deployment that already
// had it set, so that upgrading does not silently reset somebody's site.
//
// A setting that is not here stays in the environment. That is deliberate:
// the database connection cannot come from the database, and a secret that is
// generated once at install has no business being editable in a web page.

/**
 * @typedef {object} SettingDefinition
 * @property {string} key       stable id, used by the API and the UI
 * @property {string} [path]    dot path into the Settings object. Absent for
 *   a setting that is delivered by writing it back into the environment,
 *   because what reads it reads it from there.
 * @property {string} [env]     the variable this used to be read from
 * @property {string} section
 * @property {'string'|'text'|'boolean'|'number'|'password'|'select'|'json'} type
 * @property {string} label
 * @property {string} [help]
 * @property {any} [default]
 * @property {Array<{value: string, label: string}>} [options]
 * @property {boolean} [restart] true when the value is only read at startup
 */

export const SECTIONS = [
  { id: 'site', label: 'Site', help: 'What the site is called and where it lives.' },
  { id: 'registration', label: 'Sign up and sign in', help: 'Who may create an account, and how.' },
  { id: 'oauth', label: 'Sign in with Google and GitHub', help: 'Leave the client id blank to hide a provider.' },
  { id: 'email', label: 'Email', help: 'Used for invitations, password resets and notifications.' },
  { id: 'appearance', label: 'Appearance', help: 'Branding shown around the editor.' },
  { id: 'compile', label: 'Compiling', help: 'Limits applied to every LaTeX compile.' },
  { id: 'security', label: 'Security', help: 'Session and password rules.' },
  { id: 'access', label: 'Who can see what', help: 'Sharing, guests and chat.' },
  { id: 'projects', label: 'Projects', help: 'What a new project gets, and what may go into one.' },
  { id: 'texlive', label: 'TeX Live', help: 'Which TeX Live people compile with, and how isolated a compile is.' },
  { id: 'integrations', label: 'Integrations', help: 'Git, GitHub, Zotero and Mendeley. Each needs an application registered with that service.' },
  { id: 'templates', label: 'Templates', help: 'The gallery people start new projects from.' },
  { id: 'storage', label: 'Storage', help: 'Keep files and history on this server, or in S3.' },
  { id: 'enterpriseAuth', label: 'LDAP, SAML and OIDC', help: 'Sign-in against a directory or an identity provider.' },
  { id: 'cleanup', label: 'Deleting things', help: 'What happens to projects and accounts after they are deleted.' },
  { id: 'advanced', label: 'Advanced', help: 'Settings that have no field of their own yet.' },
]

/** @type {SettingDefinition[]} */
export const SETTINGS = [
  // -- site ----------------------------------------------------------------
  {
    key: 'siteUrl',
    path: 'siteUrl',
    env: 'OVERLEAF_SITE_URL',
    section: 'site',
    type: 'string',
    label: 'Site URL',
    help: 'The address people reach this site at. Links in emails and the OAuth callback are built from it, so it has to be right.',
    default: 'http://localhost',
  },
  {
    key: 'appName',
    path: 'appName',
    env: 'OVERLEAF_APP_NAME',
    section: 'site',
    type: 'string',
    label: 'Site name',
    default: 'Overleaf Community Edition',
  },
  {
    key: 'adminEmail',
    path: 'adminEmail',
    env: 'OVERLEAF_ADMIN_EMAIL',
    section: 'site',
    type: 'string',
    label: 'Administrator email',
    help: 'Shown to users as the address to contact for help.',
    default: '',
  },
  {
    key: 'siteLanguage',
    path: 'i18n.defaultLng',
    env: 'OVERLEAF_SITE_LANGUAGE',
    section: 'site',
    type: 'string',
    label: 'Default language',
    help: 'A two-letter code, or one like zh-CN. The translations are loaded once when the site starts, so this one needs a restart.',
    default: 'en',
    restart: true,
  },
  {
    key: 'statusPageUrl',
    path: 'statusPageUrl',
    env: 'OVERLEAF_STATUS_PAGE_URL',
    section: 'site',
    type: 'string',
    label: 'Status page URL',
    default: '',
  },

  // -- registration --------------------------------------------------------
  {
    key: 'allowPublicRegistration',
    path: 'siteSettings.allowPublicRegistration',
    env: 'OVERLEAF_ALLOW_PUBLIC_REGISTRATION',
    section: 'registration',
    type: 'boolean',
    label: 'Anyone may create an account',
    help: 'When this is off, only an administrator can add users. The very first account is always allowed, so a new site can be set up.',
    default: true,
  },
  {
    key: 'registrationEmailDomains',
    path: 'siteSettings.registrationEmailDomains',
    section: 'registration',
    type: 'string',
    label: 'Restrict sign up to these email domains',
    help: 'Comma separated, for example example.com, *.example.org. Leave blank to allow any address. This used to be the value of OVERLEAF_ALLOW_PUBLIC_REGISTRATION itself, written as @example.com, and a deployment that had it that way is read across.',
    default: '',
  },
  {
    key: 'emailConfirmation',
    path: 'siteSettings.emailConfirmation',
    section: 'registration',
    type: 'select',
    label: 'Confirming an email address',
    help: 'A site with no mail server cannot ask anybody to confirm anything, so the usual answer follows whether SMTP is configured.',
    options: [
      { value: 'auto', label: 'required once a mail server is configured' },
      { value: 'required', label: 'always required' },
      { value: 'off', label: 'never asked for' },
    ],
    default: 'auto',
  },
  {
    key: 'allowAnonymousReadAndWriteSharing',
    path: 'allowAnonymousReadAndWriteSharing',
    env: 'OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING',
    section: 'registration',
    type: 'boolean',
    label: 'Allow link sharing with people who have no account',
    default: false,
  },
  {
    key: 'restrictInvitesToExistingAccounts',
    path: 'restrictInvitesToExistingAccounts',
    env: 'OVERLEAF_RESTRICT_INVITES_TO_EXISTING_ACCOUNTS',
    section: 'registration',
    type: 'boolean',
    label: 'Only allow project invitations to existing accounts',
    default: false,
  },

  // -- oauth ---------------------------------------------------------------
  {
    key: 'googleClientId',
    path: 'siteSettings.oauth.google.clientId',
    env: 'OVERLEAF_GOOGLE_CLIENT_ID',
    section: 'oauth',
    type: 'string',
    label: 'Google client ID',
    help: 'From the Google Cloud console. The redirect URI to register there is <site URL>/auth/google/callback.',
    default: '',
  },
  {
    key: 'googleClientSecret',
    path: 'siteSettings.oauth.google.clientSecret',
    env: 'OVERLEAF_GOOGLE_CLIENT_SECRET',
    section: 'oauth',
    type: 'password',
    label: 'Google client secret',
    default: '',
  },
  {
    key: 'githubClientId',
    path: 'siteSettings.oauth.github.clientId',
    env: 'OVERLEAF_GITHUB_CLIENT_ID',
    section: 'oauth',
    type: 'string',
    label: 'GitHub client ID',
    help: 'From your GitHub OAuth app. The callback URL to register there is <site URL>/auth/github/callback.',
    default: '',
  },
  {
    key: 'githubClientSecret',
    path: 'siteSettings.oauth.github.clientSecret',
    env: 'OVERLEAF_GITHUB_CLIENT_SECRET',
    section: 'oauth',
    type: 'password',
    label: 'GitHub client secret',
    default: '',
  },
  {
    key: 'oauthCreatesAccounts',
    path: 'siteSettings.oauth.createsAccounts',
    section: 'oauth',
    type: 'boolean',
    label: 'Signing in with Google or GitHub may create an account',
    help: 'When this is off, someone can only sign in that way if an account with the same email already exists, or if they linked it from their account settings.',
    default: true,
  },

  // -- email ---------------------------------------------------------------
  {
    key: 'emailFromAddress',
    path: 'email.fromAddress',
    env: 'OVERLEAF_EMAIL_FROM_ADDRESS',
    section: 'email',
    type: 'string',
    label: 'From address',
    default: '',
  },
  {
    key: 'emailReplyTo',
    path: 'email.replyTo',
    env: 'OVERLEAF_EMAIL_REPLY_TO',
    section: 'email',
    type: 'string',
    label: 'Reply-to address',
    default: '',
  },
  {
    key: 'emailSmtpHost',
    path: 'email.parameters.host',
    env: 'OVERLEAF_EMAIL_SMTP_HOST',
    section: 'email',
    type: 'string',
    label: 'SMTP host',
    help: 'Leave blank to turn email off. Without it, password resets and invitations cannot be sent.',
    default: '',
  },
  {
    key: 'emailSmtpPort',
    path: 'email.parameters.port',
    env: 'OVERLEAF_EMAIL_SMTP_PORT',
    section: 'email',
    type: 'number',
    label: 'SMTP port',
    default: 587,
  },
  {
    key: 'emailSmtpSecure',
    path: 'email.parameters.secure',
    env: 'OVERLEAF_EMAIL_SMTP_SECURE',
    section: 'email',
    type: 'boolean',
    label: 'Connect with TLS',
    help: 'On for port 465. Off for 587, which upgrades the connection afterwards.',
    default: false,
  },
  {
    key: 'emailSmtpUser',
    path: 'email.parameters.auth.user',
    env: 'OVERLEAF_EMAIL_SMTP_USER',
    section: 'email',
    type: 'string',
    label: 'SMTP username',
    default: '',
  },
  {
    key: 'emailSmtpPass',
    path: 'email.parameters.auth.pass',
    env: 'OVERLEAF_EMAIL_SMTP_PASS',
    section: 'email',
    type: 'password',
    label: 'SMTP password',
    default: '',
  },
  {
    key: 'emailSmtpIgnoreTLS',
    path: 'email.parameters.ignoreTLS',
    env: 'OVERLEAF_EMAIL_SMTP_IGNORE_TLS',
    section: 'email',
    type: 'boolean',
    label: 'Do not upgrade the connection to TLS',
    default: false,
  },
  {
    key: 'emailCustomFooter',
    path: 'email.template.customFooter',
    env: 'OVERLEAF_CUSTOM_EMAIL_FOOTER',
    section: 'email',
    type: 'text',
    label: 'Footer added to every email',
    default: '',
  },

  // -- appearance ----------------------------------------------------------
  {
    key: 'navTitle',
    path: 'nav.title',
    env: 'OVERLEAF_NAV_TITLE',
    section: 'appearance',
    type: 'string',
    label: 'Title in the navigation bar',
    default: '',
  },
  {
    key: 'headerImageUrl',
    path: 'nav.custom_logo',
    env: 'OVERLEAF_HEADER_IMAGE_URL',
    section: 'appearance',
    type: 'string',
    label: 'Logo URL',
    default: '',
  },
  {
    key: 'leftFooter',
    path: 'nav.left_footer',
    env: 'OVERLEAF_LEFT_FOOTER',
    section: 'appearance',
    type: 'json',
    label: 'Left footer',
    help: 'A JSON array of {"text": "...", "url": "..."} entries.',
    default: '[]',
  },
  {
    key: 'rightFooter',
    path: 'nav.right_footer',
    env: 'OVERLEAF_RIGHT_FOOTER',
    section: 'appearance',
    type: 'json',
    label: 'Right footer',
    help: 'A JSON array of {"text": "...", "url": "..."} entries.',
    default: '[]',
  },
  {
    key: 'maintenanceMessage',
    path: 'maintenanceMessage',
    env: 'OVERLEAF_MAINTENANCE_MESSAGE',
    section: 'appearance',
    type: 'text',
    label: 'Banner shown on every page',
    help: 'Leave blank for no banner.',
    default: '',
  },

  // -- compile -------------------------------------------------------------
  {
    key: 'compileTimeout',
    path: 'defaultFeatures.compileTimeout',
    env: 'COMPILE_TIMEOUT',
    section: 'compile',
    type: 'number',
    label: 'Compile timeout, seconds',
    help: 'One of the features an account is given when it is created, so changing it applies to accounts made after the change. Existing accounts keep the timeout they were given.',
    default: 180,
  },
  {
    key: 'compileGroupDefault',
    path: 'defaultFeatures.compileGroup',
    section: 'compile',
    type: 'select',
    label: 'Compile group for new users',
    options: [
      { value: 'standard', label: 'standard' },
      { value: 'priority', label: 'priority' },
    ],
    default: 'standard',
  },

  // -- security ------------------------------------------------------------
  {
    key: 'secureCookie',
    path: 'secureCookie',
    env: 'OVERLEAF_SECURE_COOKIE',
    section: 'security',
    type: 'boolean',
    label: 'Only send the session cookie over HTTPS',
    help: 'Turn this on once the site is served over HTTPS. With it on and the site on plain HTTP, nobody can sign in.',
    default: false,
    restart: true,
  },
  {
    key: 'cookieSessionLength',
    path: 'cookieSessionLength',
    env: 'OVERLEAF_COOKIE_SESSION_LENGTH',
    section: 'security',
    type: 'number',
    label: 'How long a session lasts, seconds',
    default: 5 * 24 * 60 * 60,
    restart: true,
  },
  {
    key: 'passwordMinLength',
    path: 'passwordStrengthOptions.length.min',
    env: 'OVERLEAF_PASSWORD_VALIDATION_MIN_LENGTH',
    section: 'security',
    type: 'number',
    label: 'Minimum password length',
    default: 8,
  },
  {
    key: 'passwordMaxLength',
    path: 'passwordStrengthOptions.length.max',
    env: 'OVERLEAF_PASSWORD_VALIDATION_MAX_LENGTH',
    section: 'security',
    type: 'number',
    label: 'Maximum password length',
    default: 72,
  },

  // Everything below is delivered by putting it back into the environment
  // rather than into Settings: what reads these decides at import time whether
  // a feature exists at all, so they take effect when the site restarts. A row
  // with no `path` is one of those.
  {
    key: 'allowPublicAccess',
    path: 'allowPublicAccess',
    env: 'OVERLEAF_ALLOW_PUBLIC_ACCESS',
    section: 'access',
    type: 'boolean',
    label: 'Let people open shared links without an account',
    help: 'Off means everybody is sent to sign in first, even with a valid sharing link.',
    default: false,
  },
  {
    key: 'disableLinkSharing',
    path: 'disableLinkSharing',
    env: 'OVERLEAF_DISABLE_LINK_SHARING',
    section: 'access',
    type: 'boolean',
    label: 'Turn off link sharing entirely',
    help: 'Projects can then only be shared by inviting a named account.',
    default: false,
  },
  {
    key: 'disableChat',
    path: 'disableChat',
    env: 'OVERLEAF_DISABLE_CHAT',
    section: 'access',
    type: 'boolean',
    label: 'Turn off the chat inside projects',
    default: false,
  },
  {
    key: 'loginSupportText',
    path: 'nav.login_support_text',
    env: 'OVERLEAF_LOGIN_SUPPORT_TEXT',
    section: 'access',
    type: 'text',
    label: 'Text under the sign-in button',
    help: 'HTML is allowed. Use it to say who to ask for an account.',
    default: '',
  },
  {
    key: 'defaultCompiler',
    path: 'defaultFeatures.compiler',
    env: 'DEFAULT_LATEX_COMPILER',
    section: 'projects',
    type: 'select',
    label: 'Compiler for new projects',
    options: [
      { value: 'pdflatex', label: 'pdflatex' },
      { value: 'latex', label: 'latex' },
      { value: 'xelatex', label: 'xelatex' },
      { value: 'lualatex', label: 'lualatex' },
    ],
    default: 'pdflatex',
  },
  {
    key: 'maxUploadSize',
    env: 'MAX_UPLOAD_SIZE',
    section: 'projects',
    type: 'number',
    label: 'Largest upload, in megabytes',
    help: 'Also written into the nginx config when the container starts, so this one needs a restart.',
    default: 50,
    restart: true,
  },
  {
    key: 'compileSizeLimit',
    env: 'COMPILE_SIZE_LIMIT',
    section: 'projects',
    type: 'string',
    label: 'Largest compile request',
    help: 'A size, the way the body parser reads it: 7mb, 512kb. clsi refuses a compile whose files add up to more than this.',
    default: '7mb',
    restart: true,
  },
  {
    key: 'additionalTextExtensions',
    path: 'additionalTextExtensions',
    env: 'ADDITIONAL_TEXT_EXTENSIONS',
    section: 'projects',
    type: 'string',
    label: 'Extra file extensions to treat as editable text',
    help: 'Comma separated, without the dot. For example: cls,sty,bst',
    default: '',
  },
  {
    key: 'enabledLinkedFileTypes',
    env: 'ENABLED_LINKED_FILE_TYPES',
    section: 'projects',
    type: 'string',
    label: 'Kinds of linked file people may add',
    help: 'Comma separated. zotero and mendeley are added on their own when those integrations are configured.',
    default: 'project_file,project_output_file',
    restart: true,
  },
  {
    key: 'historyInitializeNewProjects',
    env: 'OVERLEAF_FPH_INITIALIZE_NEW_PROJECTS',
    section: 'projects',
    type: 'boolean',
    label: 'Give new projects full project history',
    default: true,
    restart: true,
  },
  {
    key: 'historyDisplayNewProjects',
    env: 'OVERLEAF_FPH_DISPLAY_NEW_PROJECTS',
    section: 'projects',
    type: 'boolean',
    label: 'Show project history to people',
    default: true,
    restart: true,
  },
  {
    key: 'maintenanceMessageHtml',
    path: 'maintenanceMessageHTML',
    env: 'OVERLEAF_MAINTENANCE_MESSAGE_HTML',
    section: 'projects',
    type: 'text',
    label: 'Maintenance page body, as HTML',
    default: '',
  },
  {
    key: 'cronResourceDeletion',
    env: 'ENABLE_CRON_RESOURCE_DELETION',
    section: 'cleanup',
    type: 'boolean',
    label: 'Delete soft-deleted projects and accounts for good',
    help: 'A nightly job. Without it, deleted projects and accounts are kept until somebody removes them by hand.',
    default: false,
    restart: true,
  },
  {
    key: 'userDeletionDelay',
    env: 'OVERLEAF_USER_HARD_DELETION_DELAY',
    section: 'cleanup',
    type: 'number',
    label: 'Wait before an account is really gone, in milliseconds',
    help: '90 days by default.',
    default: 7776000000,
    restart: true,
  },
  {
    key: 'projectDeletionDelay',
    env: 'OVERLEAF_PROJECT_HARD_DELETION_DELAY',
    section: 'cleanup',
    type: 'number',
    label: 'Wait before a project is really gone, in milliseconds',
    default: 7776000000,
    restart: true,
  },
  {
    key: 'gitBridgeEnabled',
    env: 'GIT_BRIDGE_ENABLED',
    section: 'integrations',
    type: 'boolean',
    label: 'Git access to projects',
    help: 'Needs the git-bridge container. In the compose file it is behind the git profile: docker compose --profile git up -d',
    default: false,
    restart: true,
  },
  {
    key: 'gitBridgeHost',
    env: 'GIT_BRIDGE_HOST',
    section: 'integrations',
    type: 'string',
    label: 'git-bridge host',
    default: 'git-bridge',
    restart: true,
  },
  {
    key: 'gitBridgePort',
    env: 'GIT_BRIDGE_PORT',
    section: 'integrations',
    type: 'number',
    label: 'git-bridge port',
    default: 8000,
    restart: true,
  },
  {
    key: 'githubSyncEnabled',
    env: 'GITHUB_SYNC_ENABLED',
    section: 'integrations',
    type: 'boolean',
    label: 'Sync projects with GitHub repositories',
    help: 'Needs Git access above. This is a second GitHub OAuth application, separate from the one that signs people in.',
    default: false,
    restart: true,
  },
  {
    key: 'githubSyncClientId',
    env: 'GITHUB_SYNC_CLIENT_ID',
    section: 'integrations',
    type: 'string',
    label: 'GitHub sync client ID',
    help: 'Callback URL: the site URL followed by /user/github-sync/oauth2/callback',
    default: '',
    restart: true,
  },
  {
    key: 'githubSyncClientSecret',
    env: 'GITHUB_SYNC_CLIENT_SECRET',
    section: 'integrations',
    type: 'password',
    label: 'GitHub sync client secret',
    default: '',
    restart: true,
  },
  {
    key: 'githubTokenCipherPassword',
    env: 'GITHUB_TOKEN_CIPHER_PASSWORD',
    section: 'integrations',
    type: 'password',
    label: 'GitHub token encryption password',
    help: 'Encrypts the GitHub tokens kept in the database. Changing it makes every stored token unreadable.',
    default: '',
    restart: true,
  },
  {
    key: 'githubSyncProxyUrl',
    env: 'GITHUB_SYNC_PROXY_URL',
    section: 'integrations',
    type: 'string',
    label: 'HTTP proxy for GitHub requests',
    default: '',
    restart: true,
  },
  {
    key: 'zoteroClientId',
    env: 'ZOTERO_CLIENT_ID',
    section: 'integrations',
    type: 'string',
    label: 'Zotero client ID',
    default: '',
    restart: true,
  },
  {
    key: 'zoteroClientSecret',
    env: 'ZOTERO_CLIENT_SECRET',
    section: 'integrations',
    type: 'password',
    label: 'Zotero client secret',
    default: '',
    restart: true,
  },
  {
    key: 'zoteroCipherPassword',
    env: 'ZOTERO_CIPHER_PASSWORD',
    section: 'integrations',
    type: 'password',
    label: 'Zotero key encryption password',
    default: '',
    restart: true,
  },
  {
    key: 'zoteroProxyUrl',
    env: 'ZOTERO_PROXY_URL',
    section: 'integrations',
    type: 'string',
    label: 'HTTP proxy for Zotero requests',
    default: '',
    restart: true,
  },
  {
    key: 'mendeleyClientId',
    env: 'MENDELEY_CLIENT_ID',
    section: 'integrations',
    type: 'string',
    label: 'Mendeley client ID',
    default: '',
    restart: true,
  },
  {
    key: 'mendeleyClientSecret',
    env: 'MENDELEY_CLIENT_SECRET',
    section: 'integrations',
    type: 'password',
    label: 'Mendeley client secret',
    default: '',
    restart: true,
  },
  {
    key: 'mendeleyCipherPassword',
    env: 'MENDELEY_CIPHER_PASSWORD',
    section: 'integrations',
    type: 'password',
    label: 'Mendeley token encryption password',
    default: '',
    restart: true,
  },
  {
    key: 'mendeleyProxyUrl',
    env: 'MENDELEY_PROXY_URL',
    section: 'integrations',
    type: 'string',
    label: 'HTTP proxy for Mendeley requests',
    default: '',
    restart: true,
  },
  {
    key: 'templateGallery',
    env: 'OVERLEAF_TEMPLATE_GALLERY',
    section: 'templates',
    type: 'boolean',
    label: 'Template gallery',
    default: false,
    restart: true,
  },
  {
    key: 'enableConversions',
    env: 'ENABLE_CONVERSIONS',
    section: 'templates',
    type: 'boolean',
    label: 'Generate thumbnails and previews',
    help: 'Needed by the gallery, and by image previews in projects. Uses ImageMagick inside the container.',
    default: false,
    restart: true,
  },
  {
    key: 'templateCategories',
    env: 'OVERLEAF_TEMPLATE_CATEGORIES',
    section: 'templates',
    type: 'string',
    label: 'Categories to show',
    help: 'Space separated: academic-journal book presentation poster cv homework bibliography calendar formal-letter report thesis newsletter. The key all is added on its own.',
    default: '',
    restart: true,
  },
  {
    key: 'templatesUserId',
    env: 'OVERLEAF_TEMPLATES_USER_ID',
    section: 'templates',
    type: 'string',
    label: 'Account that owns the curated templates',
    help: 'A user id. That account publishes the templates everybody sees.',
    default: '',
    restart: true,
  },
  {
    key: 'sandboxedCompiles',
    env: 'SANDBOXED_COMPILES',
    section: 'texlive',
    type: 'boolean',
    label: 'Compile each project in its own container',
    help: 'Without this every compile shares one container, so a project can read another project. The compose file also has to mount the docker socket and the two compile directories.',
    default: false,
    restart: true,
  },
  {
    key: 'imageRoot',
    env: 'IMAGE_ROOT',
    section: 'texlive',
    type: 'string',
    label: 'Where TeX Live images are pulled from',
    help: 'Change this to move to a mirror or a private registry. Existing projects follow, because an image is matched by its name and tag rather than its address.',
    default: 'ghcr.io/ayaka-notes',
    restart: true,
  },
  {
    key: 'texLiveImages',
    env: 'ALL_TEX_LIVE_DOCKER_IMAGES',
    section: 'texlive',
    type: 'string',
    label: 'TeX Live images this site offers',
    help: 'Comma separated, full references. Pull each one on the host first; nothing here pulls them.',
    default: '',
    restart: true,
  },
  {
    key: 'texLiveImageNames',
    env: 'ALL_TEX_LIVE_DOCKER_IMAGE_NAMES',
    section: 'texlive',
    type: 'string',
    label: 'What to call each of them',
    help: 'Comma separated, in the same order. For example: TeX Live 2024, TeX Live 2023',
    default: '',
    restart: true,
  },
  {
    key: 'texLiveDefaultImage',
    env: 'TEX_LIVE_DOCKER_IMAGE',
    section: 'texlive',
    type: 'string',
    label: 'Image new projects get',
    help: 'Must be one of the images above. Left blank, the first one is used.',
    default: '',
    restart: true,
  },
  {
    key: 'siblingContainersPull',
    env: 'SIBLING_CONTAINERS_PULL',
    section: 'texlive',
    type: 'boolean',
    label: 'Pull TeX Live images on startup',
    default: false,
    restart: true,
  },
  {
    key: 'filestoreBackend',
    env: 'OVERLEAF_FILESTORE_BACKEND',
    section: 'storage',
    type: 'select',
    label: 'Where uploaded files are kept',
    options: [
      { value: 'fs', label: 'on this server' },
      { value: 's3', label: 'S3' },
    ],
    default: 'fs',
    restart: true,
  },
  {
    key: 'filestoreBucket',
    env: 'OVERLEAF_FILESTORE_USER_FILES_BUCKET_NAME',
    section: 'storage',
    type: 'string',
    label: 'S3 bucket for uploaded files',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreTemplateBucket',
    env: 'OVERLEAF_FILESTORE_TEMPLATE_FILES_BUCKET_NAME',
    section: 'storage',
    type: 'string',
    label: 'S3 bucket for template files',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreS3Key',
    env: 'OVERLEAF_FILESTORE_S3_ACCESS_KEY_ID',
    section: 'storage',
    type: 'string',
    label: 'S3 access key ID for files',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreS3Secret',
    env: 'OVERLEAF_FILESTORE_S3_SECRET_ACCESS_KEY',
    section: 'storage',
    type: 'password',
    label: 'S3 secret key for files',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreS3Region',
    env: 'OVERLEAF_FILESTORE_S3_REGION',
    section: 'storage',
    type: 'string',
    label: 'S3 region for files',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreS3Endpoint',
    env: 'OVERLEAF_FILESTORE_S3_ENDPOINT',
    section: 'storage',
    type: 'string',
    label: 'S3 endpoint for files',
    help: 'Set this for MinIO or any S3 that is not AWS.',
    default: '',
    restart: true,
  },
  {
    key: 'filestoreS3PathStyle',
    env: 'OVERLEAF_FILESTORE_S3_PATH_STYLE',
    section: 'storage',
    type: 'boolean',
    label: 'Path-style URLs for files',
    help: 'MinIO and most self-hosted S3 need this on.',
    default: false,
    restart: true,
  },
  {
    key: 'historyBackend',
    env: 'OVERLEAF_HISTORY_BACKEND',
    section: 'storage',
    type: 'select',
    label: 'Where history is kept',
    options: [
      { value: 'gcs', label: 'on this server' },
      { value: 's3', label: 'S3' },
    ],
    default: 'gcs',
    restart: true,
  },
  {
    key: 'historyBlobsBucket',
    env: 'OVERLEAF_HISTORY_PROJECT_BLOBS_BUCKET',
    section: 'storage',
    type: 'string',
    label: 'S3 bucket for history blobs',
    default: '',
    restart: true,
  },
  {
    key: 'historyChunksBucket',
    env: 'OVERLEAF_HISTORY_CHUNKS_BUCKET',
    section: 'storage',
    type: 'string',
    label: 'S3 bucket for history chunks',
    default: '',
    restart: true,
  },
  {
    key: 'historyS3Key',
    env: 'OVERLEAF_HISTORY_S3_ACCESS_KEY_ID',
    section: 'storage',
    type: 'string',
    label: 'S3 access key ID for history',
    default: '',
    restart: true,
  },
  {
    key: 'historyS3Secret',
    env: 'OVERLEAF_HISTORY_S3_SECRET_ACCESS_KEY',
    section: 'storage',
    type: 'password',
    label: 'S3 secret key for history',
    default: '',
    restart: true,
  },
  {
    key: 'historyS3Region',
    env: 'OVERLEAF_HISTORY_S3_REGION',
    section: 'storage',
    type: 'string',
    label: 'S3 region for history',
    default: '',
    restart: true,
  },
  {
    key: 'historyS3Endpoint',
    env: 'OVERLEAF_HISTORY_S3_ENDPOINT',
    section: 'storage',
    type: 'string',
    label: 'S3 endpoint for history',
    default: '',
    restart: true,
  },
  {
    key: 'historyS3PathStyle',
    env: 'OVERLEAF_HISTORY_S3_PATH_STYLE',
    section: 'storage',
    type: 'boolean',
    label: 'Path-style URLs for history',
    default: false,
    restart: true,
  },
  {
    key: 'externalAuth',
    env: 'EXTERNAL_AUTH',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'External sign-in to switch on',
    help: 'Comma separated: ldap, saml, oidc. Leave blank for none. Google and GitHub are not set here; they are above.',
    default: '',
    restart: true,
  },
  {
    key: 'ldapUrl',
    env: 'OVERLEAF_LDAP_URL',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP URL',
    help: 'For example: ldap://ldap.example.com:389',
    default: '',
    restart: true,
  },
  {
    key: 'ldapSearchBase',
    env: 'OVERLEAF_LDAP_SEARCH_BASE',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP search base',
    default: '',
    restart: true,
  },
  {
    key: 'ldapSearchFilter',
    env: 'OVERLEAF_LDAP_SEARCH_FILTER',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP search filter',
    default: '',
    restart: true,
  },
  {
    key: 'ldapBindDn',
    env: 'OVERLEAF_LDAP_BIND_DN',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP bind DN',
    default: '',
    restart: true,
  },
  {
    key: 'ldapBindCredentials',
    env: 'OVERLEAF_LDAP_BIND_CREDENTIALS',
    section: 'enterpriseAuth',
    type: 'password',
    label: 'LDAP bind password',
    default: '',
    restart: true,
  },
  {
    key: 'ldapEmailAtt',
    env: 'OVERLEAF_LDAP_EMAIL_ATT',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP attribute holding the email',
    default: 'mail',
    restart: true,
  },
  {
    key: 'ldapNameAtt',
    env: 'OVERLEAF_LDAP_NAME_ATT',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP attribute holding the first name',
    default: 'cn',
    restart: true,
  },
  {
    key: 'ldapLastNameAtt',
    env: 'OVERLEAF_LDAP_LAST_NAME_ATT',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'LDAP attribute holding the last name',
    default: 'sn',
    restart: true,
  },
  {
    key: 'ldapIdentityServiceName',
    env: 'OVERLEAF_LDAP_IDENTITY_SERVICE_NAME',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'What the LDAP button says',
    default: '',
    restart: true,
  },
  {
    key: 'ldapUpdateOnLogin',
    env: 'OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN',
    section: 'enterpriseAuth',
    type: 'boolean',
    label: 'Refresh names from LDAP on every sign-in',
    default: false,
    restart: true,
  },
  {
    key: 'samlEntrypoint',
    env: 'OVERLEAF_SAML_ENTRYPOINT',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'SAML entry point URL',
    default: '',
    restart: true,
  },
  {
    key: 'samlIssuer',
    env: 'OVERLEAF_SAML_ISSUER',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'SAML issuer',
    default: '',
    restart: true,
  },
  {
    key: 'samlIdpCert',
    env: 'OVERLEAF_SAML_IDP_CERT',
    section: 'enterpriseAuth',
    type: 'text',
    label: 'SAML identity provider certificate',
    default: '',
    restart: true,
  },
  {
    key: 'samlEmailField',
    env: 'OVERLEAF_SAML_EMAIL_FIELD',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'SAML field holding the email',
    default: '',
    restart: true,
  },
  {
    key: 'samlFirstNameField',
    env: 'OVERLEAF_SAML_FIRST_NAME_FIELD',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'SAML field holding the first name',
    default: '',
    restart: true,
  },
  {
    key: 'samlLastNameField',
    env: 'OVERLEAF_SAML_LAST_NAME_FIELD',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'SAML field holding the last name',
    default: '',
    restart: true,
  },
  {
    key: 'samlIdentityServiceName',
    env: 'OVERLEAF_SAML_IDENTITY_SERVICE_NAME',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'What the SAML button says',
    default: '',
    restart: true,
  },
  {
    key: 'oidcIssuer',
    env: 'OVERLEAF_OIDC_ISSUER',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC issuer',
    default: '',
    restart: true,
  },
  {
    key: 'oidcClientId',
    env: 'OVERLEAF_OIDC_CLIENT_ID',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC client ID',
    default: '',
    restart: true,
  },
  {
    key: 'oidcClientSecret',
    env: 'OVERLEAF_OIDC_CLIENT_SECRET',
    section: 'enterpriseAuth',
    type: 'password',
    label: 'OIDC client secret',
    default: '',
    restart: true,
  },
  {
    key: 'oidcAuthorizationUrl',
    env: 'OVERLEAF_OIDC_AUTHORIZATION_URL',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC authorization URL',
    default: '',
    restart: true,
  },
  {
    key: 'oidcTokenUrl',
    env: 'OVERLEAF_OIDC_TOKEN_URL',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC token URL',
    default: '',
    restart: true,
  },
  {
    key: 'oidcUserInfoUrl',
    env: 'OVERLEAF_OIDC_USER_INFO_URL',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC user info URL',
    default: '',
    restart: true,
  },
  {
    key: 'oidcScope',
    env: 'OVERLEAF_OIDC_SCOPE',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'OIDC scopes',
    default: 'openid profile email',
    restart: true,
  },
  {
    key: 'oidcIdentityServiceName',
    env: 'OVERLEAF_OIDC_IDENTITY_SERVICE_NAME',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'What the OIDC button says',
    default: '',
    restart: true,
  },
  {
    key: 'oidcAllowedEmailDomains',
    env: 'OVERLEAF_OIDC_ALLOWED_EMAIL_DOMAINS',
    section: 'enterpriseAuth',
    type: 'string',
    label: 'Email domains OIDC may sign in',
    default: '',
    restart: true,
  },
  {
    key: 'extraEnvironment',
    section: 'advanced',
    type: 'text',
    label: 'Anything else, as NAME=value lines',
    help: 'One per line. These are put into the environment before any module is loaded, which is how everything above works too. Use it for settings that have no field of their own yet.',
    default: '',
    restart: true,
  },
]

const BY_KEY = new Map(SETTINGS.map(setting => [setting.key, setting]))

export function definitionFor(key) {
  return BY_KEY.get(key)
}

/** A value that is never sent to the browser in full. */
export function isSecret(definition) {
  return definition.type === 'password'
}
