package docupdater

import (
	"bufio"
	"encoding/json"
	"io"
	"math/rand/v2"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/Uniseem/ayakaleaf-pro/services-go/internal/textot"
)

// A write through the HTTP API arrives as the finished document and is turned
// into an edit by diffing it against what is there. Two implementations can
// each find a correct difference and find different ones: the document comes
// out the same either way, and the operation the other editors see, the one the
// tracked changes move against, and the one recorded in the history are all
// different.
//
// So the diff is compared against the real DiffCodec over random documents,
// the same way the OT transform is.
//
//	DOCUPDATER_NODE_DIR=/build/services/document-updater \
//	  go test ./internal/docupdater/ -run DiffDifferential

var diffDifferentialCases = envInt("DIFF_CODEC_CASES", 20000)

func envInt(name string, fallback int) int {
	if raw := os.Getenv(name); raw != "" {
		if value, err := strconv.Atoi(raw); err == nil {
			return value
		}
	}
	return fallback
}

type diffScenario struct {
	Before []string `json:"before"`
	After  []string `json:"after"`
}

type diffResult struct {
	Op    json.RawMessage `json:"op"`
	Error string          `json:"error"`
}

func TestDiffDifferentialAgainstNode(t *testing.T) {
	nodeDir := os.Getenv("DOCUPDATER_NODE_DIR")
	if nodeDir == "" {
		t.Skip("set DOCUPDATER_NODE_DIR to the document-updater service to run this")
	}
	nodeDir, err := filepath.Abs(nodeDir)
	if err != nil {
		t.Fatalf("resolving DOCUPDATER_NODE_DIR: %v", err)
	}

	scenarios := generateDiffScenarios(diffDifferentialCases)
	results := runDiffHarness(t, nodeDir, scenarios)
	if len(results) != len(scenarios) {
		t.Fatalf("the harness returned %d results for %d scenarios",
			len(results), len(scenarios))
	}

	for i, scenario := range scenarios {
		if results[i].Error != "" {
			t.Fatalf("case %d: the Node diff failed: %s", i, results[i].Error)
		}
		got, err := json.Marshal(diffAsShareJSOp(scenario.Before, scenario.After))
		if err != nil {
			t.Fatalf("case %d: encoding the op: %v", i, err)
		}
		if !sameJSON(string(results[i].Op), string(got)) {
			t.Fatalf("case %d\n  before: %q\n  after:  %q\n  node: %s\n  go:   %s",
				i, scenario.Before, scenario.After, results[i].Op, got)
		}

		// Whatever the two agreed on, it has to rebuild the document. An
		// agreed-on wrong answer would otherwise pass unnoticed.
		var op textot.Op
		if err := json.Unmarshal(got, &op); err != nil {
			t.Fatalf("case %d: decoding the op: %v", i, err)
		}
		rebuilt, err := textot.Apply(textot.JoinLines(scenario.Before), op)
		if err != nil {
			t.Fatalf("case %d: applying the op: %v", i, err)
		}
		if want := textot.JoinLines(scenario.After); rebuilt.String() != want.String() {
			t.Fatalf("case %d: the diff does not rebuild the document\n  want: %q\n  got:  %q",
				i, want.String(), rebuilt.String())
		}
	}
}

// generateDiffScenarios builds pairs of documents to diff.
//
// They are generated by editing a document rather than by drawing two at
// random: two unrelated documents have no interesting boundaries to align, and
// the boundaries are where the two implementations can disagree.
func generateDiffScenarios(count int) []diffScenario {
	random := rand.New(rand.NewPCG(9, 24))

	// The vocabulary is small on purpose, so the same words turn up in
	// different places and the diff has to choose between them.
	words := []string{"the", "quick", "brown", "fox", "café", "中文", "🎉",
		`\section{intro}`, `\textbf{bold}`, "x", "a.", "  indented", ""}

	scenarios := make([]diffScenario, 0, count)
	for len(scenarios) < count {
		// Documents of both sizes: a short one is compared character by
		// character, and one over a hundred characters is compared line by
		// line first, which is a different path through the algorithm.
		lines := 1 + random.IntN(6)
		if random.IntN(3) == 0 {
			lines = 8 + random.IntN(40)
		}
		before := make([]string, lines)
		for i := range before {
			var line strings.Builder
			for w := random.IntN(5); w > 0; w-- {
				line.WriteString(words[random.IntN(len(words))])
				if random.IntN(2) == 0 {
					line.WriteByte(' ')
				}
			}
			before[i] = line.String()
		}

		after := append([]string(nil), before...)
		for edits := 1 + random.IntN(3); edits > 0; edits-- {
			switch random.IntN(6) {
			case 0: // a line rewritten
				if len(after) > 0 {
					after[random.IntN(len(after))] = words[random.IntN(len(words))]
				}
			case 1: // a line added
				at := random.IntN(len(after) + 1)
				after = append(after[:at], append([]string{words[random.IntN(len(words))]},
					after[at:]...)...)
			case 2: // a line removed
				if len(after) > 1 {
					at := random.IntN(len(after))
					after = append(after[:at], after[at+1:]...)
				}
			case 3: // a word appended to a line
				if len(after) > 0 {
					at := random.IntN(len(after))
					after[at] += " " + words[random.IntN(len(words))]
				}
			case 4: // two lines swapped
				if len(after) > 1 {
					i, j := random.IntN(len(after)), random.IntN(len(after))
					after[i], after[j] = after[j], after[i]
				}
			case 5: // a line split in two
				if len(after) > 0 {
					at := random.IntN(len(after))
					line := []rune(after[at])
					if len(line) > 1 {
						cut := 1 + random.IntN(len(line)-1)
						after = append(after[:at], append([]string{
							string(line[:cut]), string(line[cut:]),
						}, after[at+1:]...)...)
					}
				}
			}
		}
		scenarios = append(scenarios, diffScenario{Before: before, After: after})
	}
	return scenarios
}

// runDiffHarness puts every scenario through the Node harness in one process.
func runDiffHarness(t *testing.T, nodeDir string, scenarios []diffScenario) []diffResult {
	t.Helper()

	harness, err := filepath.Abs(filepath.Join("testdata", "diffharness.js"))
	if err != nil {
		t.Fatalf("resolving the harness: %v", err)
	}
	cmd := exec.Command("node", harness, nodeDir)
	cmd.Stderr = os.Stderr

	stdin, err := cmd.StdinPipe()
	if err != nil {
		t.Fatalf("stdin: %v", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatalf("stdout: %v", err)
	}
	if err := cmd.Start(); err != nil {
		t.Skipf("cannot run node: %v", err)
	}

	go func() {
		writer := bufio.NewWriter(stdin)
		for _, scenario := range scenarios {
			encoded, err := json.Marshal(scenario)
			if err != nil {
				break
			}
			_, _ = writer.Write(encoded)
			_ = writer.WriteByte('\n')
		}
		_ = writer.Flush()
		_ = stdin.Close()
	}()

	var results []diffResult
	reader := bufio.NewReaderSize(stdout, 1<<20)
	for {
		line, err := reader.ReadBytes('\n')
		if len(strings.TrimSpace(string(line))) > 0 {
			var result diffResult
			// The service prints a settings banner before anything else; a
			// line that is not a result is not one.
			if err := json.Unmarshal(line, &result); err == nil {
				results = append(results, result)
			}
		}
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("reading from the harness: %v", err)
		}
	}
	if err := cmd.Wait(); err != nil {
		t.Fatalf("the harness exited badly: %v", err)
	}
	return results
}
