#!/bin/bash

# services-go/cmd/document-updater.

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /overleaf/bin/go/document-updater >> /var/log/overleaf/document-updater.log 2>&1
